BP-984 - stream logs from message server to backend
MOV-AI/backend pull request #161
Opened 2023-09-21 12:40 UTC by erezz-mov-ai

[BP-984](https://movai.atlassian.net/browse/BP-984) - stream logs from message server to backend

2023-10-04 06:41 UTC, Mograbi requested changes

2023-10-04 06:41 UTC, Mograbi commented on backend/core/log_streamer/filter.py
> +class ListParam(StrParam):
why ListParam inheriting from StrParam ??

2023-10-04 06:41 UTC, Mograbi commented on backend/core/log_streamer/filter.py
> +    def __init__(self, **params):
can you please add Doc String in order to understand better the purpose ?

2023-10-04 06:41 UTC, Mograbi commented on backend/core/log_streamer/log_streamer.py
> +            await self.handle(msg)
shouldn't we run the handle in a seperate thread in order not to block the main listener loop ?

2023-10-15 10:38 UTC, engdorm requested changes
why not use beartype 
as you did in message server

2023-10-16 08:08 UTC, erezz-mov-ai commented on backend/core/log_streamer/filter.py
> +class ListParam(StrParam):
well it was long time ago and I can't remember the exact reason, but it's working!

2023-10-16 08:10 UTC, erezz-mov-ai commented on backend/core/log_streamer/log_streamer.py
> +            await self.handle(msg)
after testing it with a running simulation currently it's not required!

2023-11-05 23:36 UTC, merged