Feature/lock mutex - Update backend project from movai_classes
MOV-AI/backend pull request #52
Opened 2022-07-05 17:07 UTC by MatheusFernandes-Movai

[FP-885](https://movai.atlassian.net/browse/FP-885)

[FP-885]: https://movai.atlassian.net/browse/FP-885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-07-10 07:45 UTC, Mograbi requested changes

2022-07-10 07:45 UTC, Mograbi commented on backend/endpoints/api/v1/restapi.py
> +from deprecated.api.models.lock import Lock
from dal.models import Lock

2022-07-13 08:23 UTC, MatheusFernandes-Movai commented on backend/endpoints/api/v1/restapi.py
> +from deprecated.api.models.lock import Lock
thank you!

2022-11-14 08:44 UTC, engdorm approved these changes

2023-02-26 12:17 UTC, quirinpa approved these changes

2023-02-26 12:17 UTC, quirinpa requested changes
Sorry its drafted and it has conflicts

2024-09-24 13:05 UTC, andreparames commented
That has been opened for over two years, closing until it's needed.

2024-09-24 13:05 UTC, closed without merging